# Deploy a Dockerfile for a node app 
FROM node:alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

ENV NODE_ENV=production

RUN npm install --production

# Bundle app source
COPY . .

# EXPOSE 8080

CMD [ "node", "./src/server.js" ]

